version: '3.9'

services:

  nginx-lb:
    image: nginx:1.21.5-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure:5
    depends_on:
      - api
    ports:
      - "80:80"

  api:
      restart: always
      build: ./
      environment:
       - "APP_PORT=3000"
      ports:
       - "3000"
      volumes:
       - .:/app
       - ./error.log:/usr/src/app/error.log

  # api2:
  #     environment:
  #      - APP_PORT=2000
  #     restart: always
  #     build: ./
  #     ports:
  #      - "2000:2000"
  #     volumes:
  #      - .:/app
  #      - ./error.log:/usr/src/app/error.log